### ISSUE TITLE
Compatibility with Ubuntu

### ISSUE THREAD

**Issue by Leah9** [Leah9/screengrab#31]
This is a non urgent issue to try to make ScreenGrab work on Ubuntu..

The current issue is ....
leah@leah-vm-ubuntu:~/Documents/Code/screengrab$ /bin/python3 /home/leah/Documents/Code/screengrab/main.py
Traceback (most recent call last):
  File "/home/leah/Documents/Code/screengrab/main.py", line 31, in <module>
    main()
  File "/home/leah/Documents/Code/screengrab/main.py", line 14, in main
    root = App.MainWindow(0, 0, 1920, 1080)
  File "/home/leah/Documents/Code/screengrab/App/main_window.py", line 39, in __init__
    self.style.theme_use("vista")
  File "/usr/lib/python3.10/tkinter/ttk.py", line 522, in theme_use
    self.tk.call("ttk::setTheme", themename)

- [x] _tkinter.TclError: can't find package ttk::theme::vista
Need to detect when OS is not Windows
comment out line 39 in main_window.py to bypass
self.style.theme_use("vista")

scrot is required
sudo apt-get install scrot

**Comment by Leah9** [comment]
Mostly working but captures a blank screen.

I will investigate pyautogui capture modes. It could be capturing the wrong interface.

requires xlib
pip install xlib
no improvement

**Comment by ArielMAJ** [comment]
Idk what is "scrot" but I guess "vista" is a windows only theme. 
You can check available themes in your OS with the following code (you can paste it in a new blank file):
```
from tkinter import ttk
print(ttk.Style().theme_names())
# ('winnative', 'clam', 'alt', 'default', 'classic', 'vista', 'xpnative') # Theme available in Windows 11 (my OS)
```
From searching a bit, I found this: https://tkdocs.com/tutorial/styles.html
If you've already solved this and got vista theme to work on Ubuntu, that's amazing! If not, we could try out downloading some external theme and applying it. This way we'd be sure the GUI looks the same everywhere (hopefully).

**Comment by ArielMAJ** [comment]
In addition, GH Actions/workflows have the option to test on multiple OSs and I also ran into a problem with pyautogui in Ubuntu and MacOS. I tried my best but I couldn't get it to work.
There's actually a good chance it's the same problem you're running into. It's this same KeyError: 'DISPLAY':
https://stackoverflow.com/questions/52244164/importing-pyautogui-in-ubuntu-throwing-keyerror-display

**Comment by ArielMAJ** [comment]
I did some testing on WSL and the nearest I got to a solution was actually screen shotting through a PowerShell command and saving it to the folder (from within WSL Ubuntu). After that we could crop the desired region using PIL to get the a similar behavior to the current one.

There's still a few problems though:
1. The region captured by "get box" doesn't seem to directly correspond to the actual screen size. So we might not be able to actually crop if the "Get Box" behavior returns just random numbers (and it looks like so). 
2. I tested the above mentioned behavior with pynput and it captures the same weird mouse position as pyautogui. Their captured positions are always equal to each other, but every time I try to capture the corner of the screen its (x,y) position changes (i.e. captured position feels random).
3. I actually managed to get the correct mouse position by running pyautogui from powershell, but... would it actually work on Ubuntu or is this just a WSL thing? (I'm guessing WSL is running powershell in Windows instead of from within the wsl terminal and thus managing to get the behavior we want, but might not work in a normal linux environment).
4. Even considering we can get it to work through powershell, does ubuntu even have powershell? Users would need to install it (another dependency for this project and... this one linux users might be inclined to not like).

In case you want to test it out yourself:
```
import os

#########################################################################################
# Works in Windows
# Screen shotting and saving to img folder.
os.system(
    """
    powershell.exe /c \
        Add-Type -AssemblyName System.Windows.Forms; \
        [Windows.Forms.Sendkeys]::SendWait(\'+{Prtsc}\'); \
        $img = [Windows.Forms.Clipboard]::GetImage(); \
        $img.Save(\'./img/test-windows.jpg\', [Drawing.Imaging.ImageFormat]::Jpeg);
    """
)
# Mouse position.
os.system(
    """
    powershell.exe /c py -c 'from pyautogui import position; print(*position());'
    """
)

#########################################################################################
# Works in WSL
# Screen shotting and saving to img folder.
os.system(
    """
    powershell.exe /c "\
        Add-Type -AssemblyName System.Windows.Forms;\
        [Windows.Forms.Sendkeys]::SendWait('+{Prtsc}');\
        \$img = [Windows.Forms.Clipboard]::GetImage();\
        \$img.Save('./img/test-wsl.jpg', [Drawing.Imaging.ImageFormat]::Jpeg);"
    """
)
# Mouse position.
os.system(
    """
    powershell.exe /c 'py -c \"from pyautogui import position; print(*position());\"'
    """
)
#########################################################################################

```

When I run the script above, as it is, from Windows 11, it generates test-windows.jpg, prints the mouse position and prints an error (in the terminal, not in python) for the second group of commands.
If I run it from WSL (after deleting all test images), it prints an error (in the terminal, not in python) for the first group of commands, generates test-wsl.jpg and prints the mouse position (correctly).

Both images look the same, a full screen shot. Idk the actual behavior if you run it actually from within a full fledge Ubuntu OS separated from Windows, but it's something to give a try. Beware that running powershell commands from python is really weird (I had to play a lot with the two types of quotation marks, testing when I should or not scape them, etc).
